// web/src/components/ShowPaste.svelte
<script>
    import NavBar from './Navbar.svelte'
    import {onMount} from "svelte";

    // language=kotlin
    let content = `
    fun main() {
        println("Hello world")
    }
    `

    export let id;
    let data;
    onMount(async () => {
        console.log(id)
        const resp = await fetch(`https://us-central1-pastify-app.cloudfunctions.net/api/${id}`)
        data = await resp.json()
        console.log(data)
        content = data['content']
    });

</script>

<main class="show-paste">
    <nav class="navbar">
        <NavBar/>
        <span class="separator"></span>
        <div class="buttons">
            <button class="button">Copy and edit</button>
        </div>
    </nav>
    <pre><code>{content}</code></pre>
</main>


<style>

</style>

// web/src/views/ShowPaste.vue
<template>
    <div class="show-paste">
        <nav class="navbar">
            <Navbar />
            <span class="separator"></span>
            <div class="buttons">
                <button class="button" v-on:click="copyAndEdit">
                    Copy and edit
                </button>
            </div>
        </nav>

        <pre class="content"><code>{{paste.content}}</code></pre>
    </div>
</template>

<script>
import { fetchPaste } from '../services/PastesService'
import Navbar from '../components/Navbar'

export default {
    name: 'ShowPaste',
    components: { Navbar },
    data() {
        return {
            paste: null,
        }
    },
    async created() {
        const id = this.$route.params.id
        this.paste = await fetchPaste(id)
        console.log(this.paste)
    },
    methods: {
        copyAndEdit: function() {
            localStorage.setItem('initialContent', this.paste.content)
            this.$router.push('/')
        },
    },
}
</script>

<style lang="scss">
.content {
    padding-left: 0.5rem;
}
</style>
