// src/views/Home.vue
<!--suppress HtmlFormInputWithoutLabel -->
<template>
    <div class="home">
        <nav class="navbar">
            <NavBar />
            <span class="separator"></span>
            <div class="buttons">
                <button class="button" v-on:click="save(content)">Save</button>
                <button class="button">Reset</button>
            </div>
        </nav>

        <textarea
            class="paste-input"
            v-model="content"
            spellcheck="false"
        ></textarea>
    </div>
</template>

<style lang="scss">
.home {
    display: flex;
    flex-direction: column;

    .navbar {
        display: flex;

        .buttons {
            display: flex;
            gap: 1rem;
            align-self: center;
            margin-right: 1rem;
        }

        .separator {
            flex: 1 1 auto;
        }

        .button {
            background: transparent;
            box-shadow: 0 0 0 1.5pt #226699;
            color: #d7d7d7;
            font-size: 1rem;
            border-radius: 5pt;
            padding: 0.3em 1em 0.3em 1em;
            width: 100%;
            height: 70%;
            :focus {
                outline: orange !important; /*TODO: This doesn't work, fix it*/
            }
        }
    }

    .paste-input {
        background-color: #252525;
        font-family: Monospaced, monospace;
        color: white;
        height: 90vh;
        padding: 0.5em;
    }
}
</style>

<script>
import MarkdownIt from 'markdown-it'
import { createPaste } from '@/services/PastesService'
import NavBar from '@/components/Navbar.vue'

function save(paste) {
    console.log(paste)
    localStorage.setItem('paste', JSON.stringify(paste))
    createPaste(paste).then(it => console.log(it))
}
const mdit = MarkdownIt()
function renderMd(text) {
    return mdit.render(text)
}

// noinspection JSUnusedGlobalSymbols
export default {
    name: 'Home',
    data: function() {
        return {
            content: '',
        }
    },
    methods: {
        save,
        renderMd,
    },
    components: {
        NavBar,
    },
}
</script>

// web/src/components/Home.svelte
<script>
    import Navbar from "./Navbar.svelte";
    import { navigate } from "svelte-routing";

    let content = 'content'

    const save = async (content) => {
        console.log(content)
        const id = 'NFK8K1N5DCL5Kb7pU0WE'
        const data = { content: content }
        console.log(data)
        const str = JSON.stringify(data)
        console.log(str)
        const resp = await fetch('https://us-central1-pastify-app.cloudfunctions.net/api/', {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ content: content})
        });

        const json = await resp.json()
        console.log(json)
        navigate(`/${json.id}`, { replace: true })

    }

    const reset = () => {
        content = '';
    }

</script>

<style type="text/scss">
    .home {
        display: flex;
        flex-direction: column;

        .paste-input {
            background-color: #181818;
            font-family: 'JetBrainsMono', monospace;
            color: white;
            height: 90vh;
            padding: 0.5em;
            border: none;
        }

    }
</style>

<main class="home">
    <nav class="navbar">
        <Navbar/>
        <span class="separator"></span>
        <div class="buttons">
            <button class="button" on:click="{save(content)}">Save</button>
            <button class="button" on:click="{reset()}">Reset</button>
        </div>
    </nav>

    <textarea
            class="paste-input"
            spellcheck="false"
            bind:value={content}
    ></textarea>
</main>
