// src/components/Navbar.vue
<template>
    <div class="nav">
        <img class="logo" alt="Logo" src="../assets/logo.png" />
        <h1 class="title">Pastify</h1>
    </div>
</template>

<style lang="scss">
.nav {
    display: flex;
    flex-direction: row;
    align-content: center;
    justify-content: flex-start;
    height: 5vh;

    .logo {
        width: 3vh;
        height: 3vh;
        align-self: center;
    }

    .title {
        margin-left: 0.5rem;
        font-size: 1.6em;
        align-self: center;
        font-weight: bold;
    }
}
</style>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'

@Component
export default class NavBar extends Vue {}
</script>

// web/src/components/Navbar.svelte
<script>
    import { navigate } from "svelte-routing"
</script>

<style type="text/scss">
    nav {
        display: flex;
        align-items: center;
        margin: 0.5rem;

        .logo {
            width: 2em;
            height: 2em;
            vertical-align: middle;
        }

        .title {
            margin-left: 0.5rem;
            font-size: 1.6em;
            font-weight: bold;
            vertical-align: middle;
        }
    }
</style>

<nav on:click={() => navigate("/")}>
    <img
            class="logo"
            alt="Logo"
            src="/icon.svg"
    />
    <h1 class="title">Pastify</h1>
</nav>
